include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.al.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    use_setters_to_change_properties: false
    